[general]
output_dir = 'outputs/mscoco/audioclip_partial/audioclip_partial_sample_100_eps_16/'
model_flag = 'audioclip_partial'
training_embeds_path = 'outputs/embeddings/mscoco_audioclip_partial_training_embeddings.npy'
centroid_embeds_path = 'outputs/embeddings/audioclip_partial/mscoco_audioclip_partial_sample_100_centroid_embeddings.npy'
gpu_num = 0
epochs =  [1000]
batch_size = 20
epsilon = 16
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'vision'
dataset_flag = 'mscoco'
max_epochs=1000