[general]
output_dir = 'outputs/audiocaps/imagebind/imagebind_sample_100_eps_16/'
model_flag = 'imagebind'
centroid_embeds_path = 'outputs/embeddings/imagebind/audiocaps_imagebind_sample_100_centroid_embeddings.npy'
gpu_num = 0
epochs =  [1000]
batch_size = 20
epsilon = 0.05
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'audio'
dataset_flag = 'audiocaps'
max_epochs=1000
cross_modality = 'True'