[general]
output_dir = 'outputs/cub_200/audioclip/audioclip_sample_100_eps_16/'
model_flag = 'audioclip'
centroid_embeds_path = 'outputs/embeddings/audioclip/cub_200_audioclip_sample_100_centroid_embeddings.npy'
gpu_num = 0
epochs =  [1000]
batch_size = 20
epsilon = 16
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'vision'
dataset_flag = 'cub_200'
max_epochs=1000
cross_modality = 'True'